Add UX for importing ballot configurations automatically in BSD
votingworks/vxsuite pull request #106
Opened 2020-12-04 18:12 UTC by carolinemodic

Adds the workflow and UI to import ballot configurations that were automatically exported from EM into BSD. I wasn't entirely sure what the best UI would be for the initial "no usb" screen or the "no ballot packages found" screen so definitely open to feedback/suggestions on those. 

When ballot packages are found and one is selected to configure (everything starting with the uploading ballot 1 screen and following is unchanged from before)
![importp1](https://user-images.githubusercontent.com/14897017/101198827-ea1fce00-3618-11eb-8cf1-6c3b45efaee6.gif)

When ballot package are not automatically found but one is selected manually to configure
![importp2](https://user-images.githubusercontent.com/14897017/101198872-f7d55380-3618-11eb-9568-5c3ffc35e907.gif)

Note that the first two commits are just copying code from bmd/election-manager into bsd.

2020-12-04 18:21 UTC, carolinemodic commented on apps/bsd/src/components/ElectionConfiguration.tsx
> +      if (err.message.includes('ENOENT')) {
This feels gross, but the error is wrapped in another error by kiosk-browser so there is no code on the error I catch here which is normally what you would check for "ENOENT" on

2020-12-08 20:54 UTC, beausmith requested changes
I don't think we should use the button from the voting interface here. It's a solution for placing all the election ballot package info in one element, but it seems out of place. 

It's also not clear from the screen cast if you must unselect a configuration before selecting another configuration.

I'd like to suggest the following:

---

# Select Election Configuration

Select one of the following configurations which were automatically found on the USB drive. Optionally, you may select a custom configuration file.

| Export Date | Name | ID | |
|:-|:-|:-|:-|
| Dec 2, 2020 9:30 am | Choctaw County - 2020 General Election | 38ck3c8f | [Select] |
| Dec 2, 2020 9:30 am | Choctaw County - 2020 General Election | 38ck3c8f | [Select] |
| Dec 2, 2020 9:30 am | Choctaw County - 2020 General Election | 38ck3c8f | [Select] |
| Or custom | | | [Select Custom] |

---

2020-12-08 21:25 UTC, beausmith commented
Suggestion for Not Configured screen:

Use full-width layout, with margins on the sides. Text all left-aligned.

---

# Load Election Configuration

(USB Drive image here)

You may load an election configuration in the following methods:

- **Insert a USB drive** with election ballot packages exported from Election Manager.
- **Insert an Admin Card** into an attached card reader.
- [Manually Select Configuration File]

---

2020-12-08 22:25 UTC, beausmith commented
Suggestion for "No Ballot Packages Found" screen:

---

# No Election Ballot Package Files Found

There were no Election Ballot Package files automatically found on the inserted USB drive. Use Election Manager to export Ballot Package files to this USB drive.

You may also [Manually Select Election Ballot Package]
---

2020-12-09 19:33 UTC, carolinemodic commented on apps/bsd/src/components/Button.tsx
> +  display: inline-block;
Button already has this by default but label doesn't so I added this for LabelButton's purpose so container elements adjust their size properly

2020-12-09 20:02 UTC, carolinemodic commented
@beausmith Back to you, added screenshots in the PR description. The USB image looks a little weird to me still, there is so much blank space in the image that its hard to figure out how it should line up, but I'm also happy to just commit this and then revisit the CSS later (or have you polish it) 

@eventualbuddha would be good to get your eyes on the kiosk browser/reading file interactions here

2020-12-11 00:52 UTC, benadida approved these changes
nice, thorough testing. Looks good to me.

2020-12-11 00:52 UTC, benadida commented on apps/bsd/src/lib/usbstick.ts
> +  return new Promise((resolve) => setTimeout(resolve, 2000))
I would suggest making this longer, say 10s. Until we find a signal that confirms that the data has been written to disk, better safe than sorry, and ejecting disks doesn't happen all that often.

2020-12-11 00:52 UTC, benadida commented on apps/bsd/src/util/filenames.ts
> +const SECTION_SEPERATOR = '__'
nit: `SEPARATOR`

2020-12-11 00:52 UTC, benadida commented on apps/bsd/src/util/filenames.ts
> +const WORD_SEPERATOR = '-'
same nit: `SEPARATOR`

2020-12-11 17:50 UTC, carolinemodic commented on apps/bsd/src/util/filenames.ts
> +const SECTION_SEPERATOR = '__'
lol whoops

2020-12-11 18:28 UTC, merged