Update to a two column UI for manual data entry screen with basic validation warnings
votingworks/vxsuite pull request #456
Opened 2021-04-23 20:55 UTC by carolinemodic

This PR does two main things
 - Iterated on the UI of the manual data page, breaking it into two columns. @beausmith would love your feedback here. The sticky behavior of the second column is lovely when the summary column is short enough to not need to scroll but when there are a lot of precincts and that side of the screen ends up scrolling the behavior is a little clunky feeling and I'm not sure how to improve it. I also wasn't sure the best location for the "select precinct" dropdown, if it should be on top of the right column with the precinct-based data or on the left sidebar. 
- Adds basic validation warnings when the contest ballots don't add up to the inputted totals, these warnings are also highlighted in the summary table. They do NOT block the ability to save the data. 

https://user-images.githubusercontent.com/14897017/115928167-8c124c80-a43a-11eb-98f4-0856165b6cb3.mov

2021-04-27 16:56 UTC, beausmith commented
Reviewing this PR…

2021-04-28 01:55 UTC, carolinemodic commented
Didn't get this today so just writing out the plan before I forget: 

Remove the two column layout, instead have index page with the precinct summarys in a table as they are now with buttons to go to edit the data for each precinct. Clicking this goes to a new screen with the contest details to fill out and a save button at the bottom, saves and takes you back to the index page. From the index page you can go back to the main Tally screen but now actual saving happens. When you toggle precinct/absentee ballots various text on the page updates (summary table "Edit Absentee Ballot Data", header on the page, etc.)

2021-04-28 17:27 UTC, beausmith commented
@carolinemodic - Summery looks good other than one item: I think "actual saving" should happen anytime that results are saved for a specific precinct. When you go back to the Manual Tally index screen, you shouldn't need to save anything. If the user clicks a different tab in the UI they shouldn't "lose" any unsaved data. 

Perhaps the button to delete all manually saved data should be moved to the Manual Tally index screen?

2021-04-28 17:52 UTC, beausmith commented
@carolinemodic - Please ping me when updated with new flow.

2021-05-01 00:40 UTC, benadida commented
I'd like to leave this review to @beausmith

2021-05-24 16:11 UTC, eventualbuddha commented
Still relevant?

2021-05-28 20:58 UTC, carolinemodic commented
Updated to two screen format previously discussed with @beausmith 

Video: 

https://user-images.githubusercontent.com/14897017/120040166-f2026e80-bfba-11eb-9ee5-082f51ce8afb.mov

2021-06-01 16:01 UTC, eventualbuddha requested changes
Reviewing as "Request changes" so the Slackbot will stop pinging us about this.

2021-06-02 17:11 UTC, beausmith commented
@carolinemodic Thanks for this update! It looks great. I'd like to make some adjustments to this PR and send it back to you for review. I'll do this today.

2021-06-16 20:39 UTC, beausmith commented
Ok @carolinemodic… this branch is rebased on master and has a design applied. 

## TODO
- [ ] Some tests may not pass.
- [ ] Total Ballots Entered on index doesn't match ballots added on precinct screen because I removed the field for ballots entered.

2021-06-21 21:30 UTC, carolinemodic commented
@beausmith Back to you for review on this! We just had to explictly calculate and set the total number of ballots when we're saving the tally now that that isn't an imputable field. So this updates it to always calculate and set the number of ballots in a contest in the internal tally object when other entries for that contest are modified, and the number of ballots shown on the screen is grabbed from the internal tally where that is set instead of being calculated again.

2021-06-28 17:51 UTC, beausmith commented on apps/election-manager/src/screens/ManualDataImportPrecinctScreen.tsx
> +          <p>Enter the number of votes for each contest option.</p>
😮

2021-06-28 18:08 UTC, beausmith approved these changes
@carolinemodic - Thank you so much for updating the logic and tests on this PR. I've made one more commit to remove the buttons at the top of the data entry screen and updated the button text at the bottom of that screen. If this commit looks good to you, merge it!!

2021-06-28 19:25 UTC, merged